[project]
name = "iaeml-assignment"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "chex>=0.1.91",
    "equinox>=0.13.2",
    "flax>=0.12.0",
    "jax>=0.8.0",
    "numpy>=2.3.4",
    "optax>=0.2.6",
    "pygame>=2.6.1",
]
